### ISSUE TITLE
Upgrade module for Prestashop lastest (1.7.8.3)

### ISSUE THREAD

**Issue by celi28** [btcpayserver/prestashop-plugin#28]
**Is your feature request related to a problem? Please describe.**
Trying to use the module with prestashop v1.7.8.3, it doesn't create the order anymore.
Got "There is no order that we can process" error after payment validation.

**Describe the solution you'd like**
Fix module order creation

**Comment by BitcoinMitchell** [comment]
Thank you for the report, I'll look into it later today and get back to you.

**Comment by BitcoinMitchell** [comment]
The order creation seems to work for me (with `Order before payment`). Which `Order creation method` are you using @celi28?

**Comment by celi28** [comment]
Thank you for the awnser. @BitcoinMitchell 
I tried to work with both parameters `order after payment` and `order before payment`. None worked.
This is a fresh installation.

**Current stack :** 
- Prestashop 1.7.8.3
- BTCPay Server v1.4.4.0 (Altcoins) 

**Issue :**
![image](https://user-images.githubusercontent.com/16089668/153592565-8cfdbd99-2ff5-4140-9072-38ec80f8fad1.png)

**Related logs:**
![image](https://user-images.githubusercontent.com/16089668/153594109-ea8fecaa-68e5-4f55-a2e8-2ccac1bf00f3.png)
![image](https://user-images.githubusercontent.com/16089668/153595042-9949a8d8-f260-4b28-9154-e8a0b9e0bf39.png)

**Comment by BitcoinMitchell** [comment]
I see, looks like maybe the redirect doesn't work properly anymore (which I didn't test), since the invoice looks to be created and updated. Will have a good look in a few hours, still at work (just did a quick test on my own store).

Thank you for the logs and information!

**Comment by BitcoinMitchell** [comment]
@celi28 The few times I was able to reproduce it was because I either went back to the store before the webhook fired/was processed (when using `order after payment`) or because BTCPayServer stopped sending webhook calls (because of too many failed calls).

Could you check for me if any webhooks fired for that specified invoice, should look something like this:

![image](https://user-images.githubusercontent.com/27309467/153675170-9266b327-7111-4859-85e6-eb4a252fdf1c.png)

Also, could you check what the webhook status is under `Store Settings` -> `Webhooks`? Should look like this:

![image](https://user-images.githubusercontent.com/27309467/153679269-9504dcce-4225-4be5-a983-1e5c5e6b5c40.png)


---

I would argue that it might be a good idea to remove `order after payment` at this point in time. I don't really see the point of it and only kept it out of legacy reasons (I didn't add it). Think it might do more harm than good, especially since I cannot think of a reason why you wouldn't want to create an order as soon as the invoice exists on BTCPayServer. The status of the order is automatically updated either way 🤔 

I've already updated some of the code to be more robust, tomorrow I'll sit down and redo this flow to be more logical. Either by making the order as soon as the user is redirect to BTCPayServer or by making a fallback, but I'm leaning heavily towards the first option.
