### ISSUE TITLE
Create prestashop order after invoice paid

### ISSUE THREAD

**Issue by celi28** [btcpayserver/prestashop-plugin#40]
**Is your feature request related to a problem? Please describe.**
Cryptocurrency payment gateway have a high rate of failure. A lot of people just give out, leaving unpaid order on prestashop dashboard.
On medium shop, it's 10/15 orders cancelled per day due to crypto payment failure.

**Describe the solution you'd like**
Create order after invoice paid webhook (need fallback mechanism)
or implement kind of order deletion / hiding process when payment failed.

**Comment by BitcoinMitchell** [comment]
I could bring back the old logic, which does almost the same, but instead of throwing an error if no order was found, it would contact BTCPay Server and check if there is an invoice that has been paid. 

That way the callback being received/processed later than the user comes back wouldn't be a problem. 🤔

**Comment by celi28** [comment]
Sorry for the delay.
I coudn't find anything wierd :)

I'll keep you informed !
