### ISSUE TITLE
Cannot select BTCPayserver in Payment Preferences

### ISSUE THREAD

**Issue by treasurehunter012** [btcpayserver/prestashop-plugin#69]
Hello guys!

Prestashop 1.7.8.7
BTCPay Server - Prestashop module (v5.2.0) 
PHP 7.4
BTCPayServer 1.7.1

Installation went smoothly. API set, shop and user configured. The problem is that I cannot enable BTCPayServer for any currency.
On the image below you can see that I can select Bank Transfer for any of the shop currency but in the same time you can see there is no  selector for BTCPayServer. Tried to install/uninstall it. All other payment modules appears to be OK.

![image](https://user-images.githubusercontent.com/35257990/207909395-5d9300a4-4715-46ee-80c6-eac2a386b52d.png)

**Comment by BitcoinMitchell** [comment]
Selecting `customer currency` or `shop default currency` will allow anyone to use the module, as you can see here (my store default currency is USD, not EUR):

![image](https://user-images.githubusercontent.com/27309467/207921161-24d17d0f-9b45-4b63-9c21-435b2f101d89.png)

---

I am not 100% sure what exactly the point of the different currency selection is, but since we do not want to restrict any currencies. we use the `radio`-button option, just like PayPal:

![image](https://user-images.githubusercontent.com/27309467/207920086-95d248f2-a8af-4617-b85c-b1c671622ca0.png)

**Comment by treasurehunter012** [comment]
Thank your for your quick follow up!

Due to the fact that the selector was not aligned with BTCPayServer name, I initially thought it's some kind of global currency settings. And the thing was that nonetheless the BTCPay was enabled it did not show up during order. So I thought I should enable it but could not. Now when I checked recent releases changelog I found that if the server is syncing the btcpay payment option will be hidden.

Probably it's exactly the case, because my btcpay instance is forever syncing the LTC nodes. So will need to resolve that first and hopefully the plugin will start to work correctly.

**Comment by BitcoinMitchell** [comment]
Ah yes! If your node is still syncing the payment option will indeed be hidden (otherwise you get weird edge-cases/BTCPay Server just errors out). I thought it was better to not show it until everything is fully synced.

Let me know if your issue is resolved once the instance is fully synced. If not, we can have another look. 👍

**Comment by treasurehunter012** [comment]
> Ah yes! If your node is still syncing the payment option will indeed be hidden (otherwise you get weird edge-cases/BTCPay Server just errors out). I thought it was better to not show it until everything is fully synced.
> 
> Let me know if your issue is resolved once the instance is fully synced. If not, we can have another look. +1

Just to let you know that sync was exactly the case why BTCPay did not appear at checkout. Once nodes were synced, plugin started to work just fine. Thanks for your help!
