### ISSUE TITLE
Wrong default parameter with new installation

### ISSUE THREAD

**Issue by Donach** [btcpayserver/prestashop-plugin#92]
**Describe the bug**
When I installed the BTCpay module, out of the box, I was having issue, where the code apparently tried to submit array into bool argument when creating the Configuration object.

**To Reproduce**
1. Have a new PrestaShop 8.1.3
2. Add BTCPay module
3. Click configure
4. See Error

**Expected behavior**
Configuration tab shows normally.

**Screenshots**
![image](https://github.com/btcpayserver/prestashop-plugin/assets/39565367/13b5398f-652d-488f-b513-2e2c6a0dca07)

**Your BTCPay Environment (please complete the following information):**
- BTCPay Server Version 1.12.4 (irrelevant for this issue)
- Deployment Method: Presta - Docker, BTCPay - Start9
 - Browser Firefox

**Logs (if applicable)**
See image

**Setup Parameters**
Default

**Additional context**
It can be fixed by replacing a line in constants:
`        public const CONFIGURATION_SHARE_METADATA = 'BTCPAY_SHARE_METADATA';`
with:
`        public const CONFIGURATION_SHARE_METADATA = false;`

**Comment by BitcoinMitchell** [comment]
Thank you for the issue report! Will look into this tonight as I'm currently unable to test anything.

**Comment by Donach** [comment]
On testing some more, Even though I'm able to "see" settings, I Cannot save, new error pops up:
![image](https://github.com/btcpayserver/prestashop-plugin/assets/39565367/80f9f75b-fa93-445b-a214-b8fe5661246d)

**Comment by BitcoinMitchell** [comment]
> On testing some more, Even though I'm able to "see" settings, I Cannot save, new error pops up:

Can I assume that you used valid data for the form? If so, not great.

**Comment by Donach** [comment]
> > On testing some more, Even though I'm able to "see" settings, I Cannot save, new error pops up:
> 
> Can I assume that you used valid data for the form? If so, not great.

Yes, the problem is with my change, it botches later on on here:
![image](https://github.com/btcpayserver/prestashop-plugin/assets/39565367/dd3961ec-e526-4e75-9869-e11c53878e3c)

So I need to figure out how to fix the default values - seems like it uses some wrong reference to an array instead of the value inside the array - since I'm not PHP coder, I cannot really see the issue myself...

**Comment by BitcoinMitchell** [comment]
No worries, I'll do a deep dive and resolve it tonight. I'm already insanely happy with the thorough issue report you've given. Thanks again for that.

**Comment by Donach** [comment]
After disabling this piece of code (line 54-56) (I assumed that it should not matter, if it's bool value only, and I have it fixed to "false"), I get another issue at checkout, just as I'm about to enter into "Shipping" (so even before going to choose the payment method).
The error is long AF:
[error.log](https://github.com/btcpayserver/prestashop-plugin/files/14206454/error.log)

EDIT: That's probably as far as I can get, hope it was/is helpful. Let me know if you'd have some hotfix I can test - my eshop is not online yet, so I'm not in a hurry, but I really would love to start it with BTCPay-enabled sometime this quarter :-)

**Comment by BitcoinMitchell** [comment]
I've tried to recreate the issue, but I have not yet been able to. I've tested the flow using the latest `docker-compose` in [this MR](https://github.com/btcpayserver/prestashop-plugin/pull/93). This way I don't need to sign up/pay for cloud hosting.

## Steps taken

- Used the `docker-compose` to spin up BTCPay Server + PrestaShop.
- Created a brand new empty store in PrestaShop and BTCPay Server.
- Logged in and enabled the debug mode.
- Added the module to the PrestaShop and clicked configure, no errors.
- Setup the connection to BTCPay Server, no problems.
- Tried to do an order, all went as expected.

# Questions
- Is there anything else you can give me, info wise, like PHP version of your host? 
- You are using the latest PrestaShop + module version? 
- Does using the reset option on the module resolve your issues?
  - It resets the modules configuration, so there should be a sane default again. 

I'll keep digging as well. I can add some "hacks" (like casting the value to a `bool`, no matter what), but I rather find the root cause.

# Background information

The flow when installing and going to configure is that we store [a sane default](https://github.com/btcpayserver/prestashop-plugin/blob/6.x/modules/btcpay/src/Installer/Config.php#L34) during installation (in this case, false).

The form then calls the `FormDataProvider`, specifically [`getData()`](https://github.com/btcpayserver/prestashop-plugin/blob/6.x/modules/btcpay/src/Form/ConfigureFormDataProvider.php) which calls `Configuration::create($this->configuration)` where `$this->configuration` is a reference to the Prestashop config storage stuff. 

[`Create`](https://github.com/btcpayserver/prestashop-plugin/blob/6.x/modules/btcpay/src/Form/Data/Configuration.php#L56) takes the information needed and tries to construct the `Configuration`-model. As you can see, it does everything well, except the `$shareMetadata`. 

That said, the fact it gives an `''` for the API key is a bit weird, since [it's default value is `null`](https://github.com/btcpayserver/prestashop-plugin/blob/6.x/modules/btcpay/src/Installer/Config.php#L30) not an empty string. 

It's all very weird and confusing. It clearly doesn't work for you, but I've tried three times and I cannot reproduce it.

> **Side-note**: `CONFIGURATION_SHARE_METADATA` is a simple constant that contains the name of the configuration value, which is then used to get the saved data from Prestashop. Changing that to `false` will indeed break things.

**Comment by Donach** [comment]
Okay, could be my installatino is somehow botched.
These are the versions:
![image](https://github.com/btcpayserver/prestashop-plugin/assets/39565367/e249d172-a922-432a-a5a5-6fc78104dbf3)

Presta: 8.1.3
BTC Module: 6.0.2

Trying to do "reset" shows error message - I'll try to reinstall my presta, and import the configs and products and try again, will report back then...

**Comment by BitcoinMitchell** [comment]
If you will be re-using the same database, you might have to remove configuration there as well (or make sure to remove the module before you re-install everything). Otherwise the broken configuration value will still be there. 

As a quick fix you can also try the ZIP in [this MR](https://github.com/btcpayserver/prestashop-plugin/pull/93), which casts the value we get from the configuration for `shareMetadata` to always be a bool.

---

Thank you for providing the versions. I'll try again and test it against your exact versions (module and presta do look up-to-date).

**Comment by Donach** [comment]
> If you will be re-using the same database, you might have to remove configuration there as well (or make sure to remove the module before you re-install everything). Otherwise the broken configuration value will still be there.
> 
> As a quick fix you can also try the ZIP in [this MR](https://github.com/btcpayserver/prestashop-plugin/pull/93), which casts the value we get from the configuration for `shareMetadata` to always be a bool.
> 
> Thank you for providing the versions. I'll try again and test it against your exact versions (module and presta do look up-to-date).

Quickly tested on fresh install, without any other config, new DB all clean - and I'm still having issues.
The configure now works to get opened, but when I wanna save configuration, I get some syntax error:
![image](https://github.com/btcpayserver/prestashop-plugin/assets/39565367/e90cbd3c-eb40-469b-92d5-3462df8fc654)

Once I got error that server is not responding, but other times it's just this...

EDIT: Lol, so after just trying to save the same config like 10 times, it eventually got saved :-D... Might be my BTCpay bisheving?
Anyway, will try to run an order and will update this comment.

EDIT2: After the same issue of the big JSON error, I simply refreshed the screen and went through with order.
However, the BTCpay option is missing from the payment options:
![image](https://github.com/btcpayserver/prestashop-plugin/assets/39565367/2f86deb0-fe63-4682-896e-0ac22e499dbd)

Although I'm quite sure it's well set and enabled:
![image](https://github.com/btcpayserver/prestashop-plugin/assets/39565367/cd7f2e8e-e267-41e0-8882-8280abddbb3c)


(Sorry for Czech, I can reupload with EN translation later or tomorrow)

**Comment by BitcoinMitchell** [comment]
Is there anything in your PrestaShop/BTCPayServer logs that might explain what went wrong? For PrestaShop logs you can go to: `Advanced Settings` -> `Logs`.

---

> EDIT: Lol, so after just trying to save the same config like 10 times, it eventually got saved :-D... Might be my BTCpay bisheving?

Maybe. I just can't think of what could go wrong like that. Having said that, this would be a separate issue from this issue, which is nice for me (but still sucks for you).

**Comment by Donach** [comment]
> Is there anything in your PrestaShop/BTCPayServer logs that might explain what went wrong? For PrestaShop logs you can go to: `Advanced Settings` -> `Logs`.
> 
> > EDIT: Lol, so after just trying to save the same config like 10 times, it eventually got saved :-D... Might be my BTCpay bisheving?
> 
> Maybe. I just can't think of what could go wrong like that. Having said that, this would be a separate issue from this issue, which is nice for me (but still sucks for you).

I get plenty of seemingly same error:
![image](https://github.com/btcpayserver/prestashop-plugin/assets/39565367/b0854b6a-526d-41e6-89c7-f5f026446024)


After closer look, it might also simply be the case, that BTCPay is not really fond of the way how I set it up with reverse proxy over SSH tunnel to my Start9...
I'll try different setup over the weekend, and let you know if I still have same issue - but it could simply be connected to the connectivity issue problem...

**Comment by BitcoinMitchell** [comment]
> I get plenty of seemingly same error:
>
> ![image](https://github.com/btcpayserver/prestashop-plugin/assets/27309467/5368dbf4-14c6-4fa6-9588-4f3592623b76)

Reading the error, that does look like nothing has been received by the plugin. the first argument in `json_decode` is an empty string, which suggests to me that no data has been received.

---

> However, the BTCpay option is missing from the payment options:

That would be because the plugin could not reach your BTCPay Server. The option is only available if it can reach the server and your node is fully synced (to prevent payment issues).

**Comment by Donach** [comment]
Hey, I've tested your latest MR 6.0.3, and it seems to work now.
Funily though, when clicking the "Configure" button, I still get some weird error.
But when going through the left menu bar, and clicking directly on BTCPay under "Payments" category, it worked just fine...
So with that, I guess this issue can be closed - but it would be nice if it was possible to add some notification saying that if BTCpay communication fails, you will not see it under payments for example, I was not aware of that...
Thanks a lot for prompt replies and taking look into it! @BitcoinMitchell

**Comment by BitcoinMitchell** [comment]
> be nice if it was possible to add some notification saying that if BTCpay communication fails, you will not see it under payments for example, I was not aware of that...

Will do! I am working on improving the configuration screen as well speak. I'll also update the README.md and/or the documentation on the BTCPay Server website.

Thank you for your report and feedback!
